# Generated by Django 4.1.3 on 2022-11-16 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persons', '0001_initial'),
        ('reference_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_time', models.DateTimeField(auto_now_add=True, verbose_name='Время регистрации')),
                ('appointment_time', models.DateTimeField(verbose_name='Время приема')),
                ('cabinet', models.CharField(max_length=100, verbose_name='Кабинет')),
                ('result', models.CharField(choices=[('Услуга запланирована', 'Planned'), ('Пациент не явился', 'No Patient'), ('Услуга предоставлена', 'Provided'), ('Услуга не предоставлена', 'Not Provided')], default='Услуга запланирована', max_length=50, verbose_name='Результат')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='persons.doctor', verbose_name='Доктор')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='persons.patient', verbose_name='Пациент')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reference_info.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'Направление',
            },
        ),
        migrations.CreateModel(
            name='Conclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_time', models.DateTimeField(auto_now_add=True, verbose_name='Время регистрации')),
                ('status', models.CharField(choices=[('Вылечено', 'Hilled'), ('Летальный исход', 'Letal'), ('Хронический характер', 'Cronic'), ('В процессе лечения', 'In Hilling Process')], default='В процессе лечения', max_length=50, verbose_name='Статус')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reference_info.diagnosis', verbose_name='Услуга')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='persons.doctor', verbose_name='Доктор')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='persons.patient', verbose_name='Пациент')),
            ],
            options={
                'verbose_name': 'Заключение',
                'verbose_name_plural': 'Заключения',
            },
        ),
    ]
